FORMAT: 1A
HOST: http://localhost:5000/

# PWP Diary API

Diary is a API to track daily activities.

## Schedule Collection [/schedules/]

### List all schedules [GET]

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
                "@controls":{
                    "self":{
                        "href": "/schedules/"
                    }
                },
                "items":[
                {
                    "id": 123
                    "start_time": "2014-12-03",
                    "end_time": "2014-13-03",
                    "@controls": {
                        "self": {
                            "href":"/schedules/123/"
                    ,
                    }
                }
                ]
            }
            
+ Response 404

## Schedule [/schedules/{schedule_id}/]

+ Parameters 
    
    + schedule_id (int) - schedules unique id

### Schedule information [GET]

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
                "id": 123
                "start_time": "2014-12-03",
                "end_time": "2014-13-03",
                "@controls": {
                    "self":{
                        "href": "/schedules/123/"
                    },
                    "edit":{
                        "method":"PUT",
                        "encoding":"json",
                        "schema":{
                            "type":"object",
                            "properties":{
                                "start_time":{
                                    "description":"Start time",
                                    "type":"datetime",
                                },
                                "end_time":{
                                    "description":"End time",
                                    "type":"datetime",
                                }
                            }
                        },
                        "required":["start_time", "end_time"]
                    },
                    "add":{
                        "method":"POST",
                        "encoding":"json",
                        "schema":{
                            "type":"object",
                            "properties":{
                                "start_time":{
                                    "description":"Start time",
                                    "type":"datetime",
                                },
                                "end_time":{
                                    "description":"End time",
                                    "type":"datetime",
                                },
                                "count":{
                                    "description":"Recurring count",
                                    "type":"int"
                                },
                                "interval_days":{
                                    "description":"Recurring interval",
                                    "type":"int"
                                }
                            }
                        },
                        "required":["start_time", "end_time"]
                    },
                    "delete":{
                        "method":"DELETE"
                        "href":"/schedules/123/"
                    }
                },
                "items":[
                    {
                        "event":{
                            "@controls":{
                                "self":{
                                    "href":"/schedules/123/events/"
                                }
                            }
                        },
                        "item":{
                            "@controls":{
                                "self":{
                                    "href":"/schedules/123/items/"
                                }
                            }
                        },
                        "task":{
                            "@controls":{
                                "self":{
                                    "href":"/schedules/123/tasks/"
                                }
                            }
                        }
                    }
                ]
            }

+ Response 404

### Delete schedule [DELETE]

+ Relation: delete

+ Request 

    + Headers

            Accept: application/vnd.mason+json

+ Response 204

+ Response 404

### Create schedule [POST]

+ Relation: add

+ Request


    + Headers
            
            Accept: application/vnd.mason+json
    
    + Body
        
            {
                "start_time": "2014-12-03",
                "end_time": "2014-13-03",
                "interval_days":0,
                "count":1
            }
            
+ Response 201
    
    + Headers

            Location: /schedules/123/ 

### Edit schedule [PUT]

+ Relation: edit

+ Request
    
    + Headers
            
            Accept: application/vnd.mason+json
    
    + Body
        
            {
                "start_time": "2014-12-03",
                "end_time": "2014-13-03"
            }

+ Response 204


## Repeating schedules collection [/repeating_schedules/]

List all repeating schedules

### Get repeating schedules [GET]

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            
            }

+ Response 404

## Repeating schedule [/repeating_schedules/{repeat_id}/]

+ Parameters 
    
    + repeat_id (int) - unique id of repeating schedule


### List all schedules [GET]

Get all same schedule that is repeating

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }

+ Response 404

## Event collection [/schedules/{schedule_id}/events]

+ Parameters 
    
    + schedule_id (int) - schedules unique id

### Get events [GET]

Get all events of one schedule

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }

+ Response 404


## Event [/schedules/{schedule_id}/events/{event_id}]

+ Parameters 
    
    + schedule_id (int) - schedules unique id
    + event_id (int) - unique event id

### Get event information [GET]

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }

+ Response 404

## Item collection [/schedules/{schedule_id}/items/]

+ Parameters 
    
    + schedule_id (int) - schedules unique id


### Get items [GET]

Get all schedules items

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }
            
+ Response 404

## Item [/schedules/{schedule_id}/items/{item_id}/]

+ Parameters 
    
    + schedule_id (int) - schedules unique id
    + item_id (int) - unique item id

### Get item information [GET]

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }

+ Response 404

## Task collection [/schedules/{schedule_id}/tasks/]

+ Parameters 
    
    + schedule_id (int) - schedules unique id

### Get tasks [GET]

Get all schedules tasks

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }

+ Response 404

## Task [/schedules/{schedule_id}/tasks/{task_id}/]

+ Parameters
    
    + schedule_id (int) - schedules unique id
    + task_id (int) - unique task id


### Get task information [GET]

+ Request
    
    + Headers
        
            Accept: application/vnd.mason+json
        
+ Response 200

    + Body
        
            {
            }

+ Response 404